### PR TITLE
Fix form warnings and change number on scroll

### LINKED ISSUE #57: Fix console warnings on /large-grant-apply
Image

### LINKED ISSUE #58: [low priority] budget is changing on scroll
Macos. When you start scrolling the page and have cursor on focused `budget` input, value changes

https://github.com/user-attachments/assets/39120fb7-55c6-467a-ad02-52ad9add9e18

### LINKED ISSUE #85: Review height from buttons
Modal buttons has different sizes and paddings across all page modals. For example, Cancel button is smaller than Reject. 48px vs 52px height.

Image

_Originally posted by @rin-st in https://github.com/BuidlGuidl/ens-pg/pull/79#pullrequestreview-2774921707_

### PR DESCRIPTION
**Pull request by rin-st**
Fix form warnings on `/large-grant-apply` and `/large-grants/[grantId]` pages 
Fix FormInputNumber change on scroll
Fix modal button sizes

Closes #57 
Closes #58 
Closes #85

### CODE REVIEW

**Comment by rin-st** [comment]
Also added fix for #85 
Screenshot 2025-05-22 at 19 30 55

File: packages/nextjs/app/large-grant-apply/page.tsx [hunk 1]
```diff
@@ -138,23 +138,15 @@ const LargeGrantApply: NextPage = () => {
                     <FormTextarea
                       label="Description"
                       showMessageLength
-                      {...formMethods.register(`milestones.${index}.description`)}
-                      error={errors?.milestones?.[index]?.description?.message}
+                      {...getCommonOptions(`milestones.${index}.description`)}
```
Comment (damianmarti) [inline packages/nextjs/app/large-grant-apply/page.tsx:141]: It's not showing the error message on milestone **Description** and **Detail of Deliverables** when you leave the field blank or with less than 20 chars.

File: packages/nextjs/app/large-grants/[grantId]/_components/CurrentStage/NewStageModal/index.tsx [hunk 2]
```diff
@@ -115,27 +110,18 @@ export const NewStageModal = forwardRef<HTMLDialogElement, NewStageModalProps>(
                         <FormTextarea
                           label="Description"
                           showMessageLength
-                          {...formMethods.register(`milestones.${index}.description`)}
-                          error={errors?.milestones?.[index]?.description?.message}
+                          {...getCommonOptions(`milestones.${index}.description`)}
```
Comment (damianmarti) [inline packages/nextjs/app/large-grants/[grantId]/_components/CurrentStage/NewStageModal/index.tsx:113]: Not tested, but I think the same will happen here.

File: packages/nextjs/components/pg-ens/form-fields/FormInputNumber.tsx [hunk 3]
```diff
@@ -30,6 +30,7 @@ export const FormInputNumber = ({ error, label, name, required }: FormInputProps
           type="number"
           min="1"
           placeholder="0"
+          onWheel={e => e.currentTarget.blur()}
```
Comment (damianmarti) [inline packages/nextjs/components/pg-ens/form-fields/FormInputNumber.tsx:33]: wow! I didn't know about this onWheel handler! :-)

**Review by damianmarti — CHANGES_REQUESTED** [review]
Thanks @rin-st for all these fixes!!

Added some comments about form errors.

Everything else looks great!

File: packages/nextjs/app/large-grants/[grantId]/_components/CurrentStage/NewStageModal/index.tsx (hunk 2 above)
Comment (rin-st) [reply packages/nextjs/app/large-grants/[grantId]/_components/CurrentStage/NewStageModal/index.tsx:113]: fixed [8a64e4b](https://github.com/BuidlGuidl/ens-pg/pull/105/commits/8a64e4b5c711d9a4f090670a0749a1c4cc4c1fd6)

also removed min=1 for number input since when submitting form it showed only that item error

**Review by damianmarti — APPROVED** [review]
Working all good now! Thanks!

**Review by Pabl0cks — APPROVED** [review]
LGTM! Thx @rin-st 🙌
