### PR TITLE
Fix TG bot notifications and add notifications to milestone completion

### LINKED ISSUE #64: Test Telegram bot for USDC grants
When a new USDC grant is created, or a builder apply for a new stage.

### PR DESCRIPTION
**Pull request by damianmarti**
This PR fixes the notifications for large grants and new large grant stages. And add notifications when a milestone from a USDC grant is completed.

This needs to be tested after https://github.com/BuidlGuidl/ens-pg-admin-bot/pull/2 is merged.

This needs to run the telegram bot locally.

fixes #64

### CODE REVIEW

File: packages/nextjs/app/api/large-milestones/[milestoneId]/review/route.ts [hunk 1]
```diff
@@ -118,6 +119,10 @@ export async function POST(req: NextRequest, { params }: { params: { milestoneId
       }
     }
 
+    if (status === "completed") {
+      await notifyTelegramBot("largeMilestone", { largeMilestone: milestone });
+    }
+
```
Comment (Pabl0cks) [inline packages/nextjs/app/api/large-milestones/[milestoneId]/review/route.ts:125]: I was receiving an error on the Telegram bot when Completing a milestone, it was not firing the message.

Seemed like it was sending the old data for the milestone (`status` = "approved" `completionProof` = NULL).

Had to tweak this to make it work:

```
    if (status === "completed") {
      // Fetch the updated milestone
      const updatedMilestone = await getMilestoneByIdWithRelatedData(Number(milestoneId));
      console.log("Milestone sent to bot:", updatedMilestone);
      await notifyTelegramBot("largeMilestone", { largeMilestone: updatedMilestone });
    }
```

<details><summary>This is the error i was getting</summary>

```
Error processing milestone webhook: ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      "largeMilestone",
      "completionProof"
    ],
    "message": "Expected string, received null"
  }
]
    at Object.get error [as error] (E:\GitHub\ens-pg-admin-bot\node_modules\zod\lib\types.js:55:31)
    at ZodObject.parse (E:\GitHub\ens-pg-admin-bot\node_modules\zod\lib\types.js:131:22)
    at E:\GitHub\ens-pg-admin-bot\src\index.ts:67:56
    at Layer.handle [as handle_request] (E:\GitHub\ens-pg-admin-bot\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\GitHub\ens-pg-admin-bot\node_modules\express\lib\router\route.js:149:13)
    at validateWebhookSecret (E:\GitHub\ens-pg-admin-bot\src\middleware\auth.ts:12:3)
    at Layer.handle [as handle_request] (E:\GitHub\ens-pg-admin-bot\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\GitHub\ens-pg-admin-bot\node_modules\express\lib\router\route.js:149:13)
    at Route.dispatch (E:\GitHub\ens-pg-admin-bot\node_modules\express\lib\router\route.js:119:3)
    at Layer.handle [as handle_request] (E:\GitHub\ens-pg-admin-bot\node_modules\express\lib\router\layer.js:95:5) {
  issues: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ],
  addIssue: [Function (anonymous)],
  addIssues: [Function (anonymous)],
  errors: [
    {
      code: 'invalid_type',
      expected: 'string',
      received: 'null',
      path: [Array],
      message: 'Expected string, received null'
    }
  ]
}
```
</details>

**Review by Pabl0cks — COMMENTED** [review]
Thx @damianmarti for tackling this! 🔥

It was working nicely except for the Milestione completion, added a comment there 🙏

File: packages/nextjs/app/api/large-milestones/[milestoneId]/review/route.ts (hunk 1 above)
Comment (damianmarti) [reply packages/nextjs/app/api/large-milestones/[milestoneId]/review/route.ts]: Thanks @Pabl0cks !

Yes, I was using a rejected milestone to test it, so the completionProof data was previously saved, so I wasn't getting this error.

It's fixed now, using the code you proposed!

**Review by Pabl0cks — APPROVED** [review]
Looks good to me!! 🔥
